name: Airbase CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy-staging:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Airbase CLI
        run: npm install --global @airbase/airbase-cli@containers

      - name: Build Docker image
        run: airbase container build

      - name: Deploy to Staging
        run: airbase container deploy --yes staging
        env:
          AIRBASE_ACCESS_KEY_ID: ${{ secrets.AIRBASE_ACCESS_KEY_ID }}
          AIRBASE_SECRET_ACCESS_KEY: ${{ secrets.AIRBASE_SECRET_ACCESS_KEY }}

  deploy-production:
    runs-on: ubuntu-latest
    needs: build-and-deploy-staging
    environment: production
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Airbase CLI
        run: npm install --global @airbase/airbase-cli@containers

      - name: Build Docker image
        run: airbase container build

      - name: Deploy to Production
        run: airbase container deploy --yes
        env:
          AIRBASE_ACCESS_KEY_ID: ${{ secrets.AIRBASE_ACCESS_KEY_ID }}
          AIRBASE_SECRET_ACCESS_KEY: ${{ secrets.AIRBASE_SECRET_ACCESS_KEY }}